{{- if .Values.pgadmin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-dep
spec:
  replicas: {{ .Values.pgadmin.replicas }}
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      initContainers:
        - name: pgadmin-init
          image: alpine
          command:
            - /bin/sh
            - -c
            - "chmod -R 777 /var/lib/pgadmin"
          volumeMounts:
            - name: pgadmin-data
              mountPath: /var/lib/pgadmin

      containers:
      - name: pgadmin
        image: {{ .Values.pgadmin.image }}
        envFrom:
          - configMapRef:
              name: pgadmin-secret
        ports:
        - containerPort: 5050
        volumeMounts:
        - name: pgadmin-data
          mountPath: /var/lib/pgadmin

      volumes:
      - name: pgadmin-data
        persistentVolumeClaim:
          claimName: pgadmin-volume-claim
{{- end }}
