apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: harbor.cs.pib.nask.pl/qss_project/users
        ports:
        - containerPort: 8001

---

apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  type: ClusterIP

