{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: nginx
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: api
        image: {{ .Values.registry }}/{{ .Values.api.image }}:{{.Values.api.tag}}
        ports:
        - containerPort: 80
{{- end }}
